receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  filelog:
    include:
      - /var/log/*.log
    start_at: beginning

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000

  resource:
    attributes:
      - key: service.name
        value: "hng-stage6"
        action: upsert
      - key: environment
        value: "production"
        action: upsert

exporters:
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  debug:
    verbosity: basic

service:
  pipelines:
    logs:
      receivers:
        - otlp
        - filelog
      processors:
        - resource
        - batch
      exporters:
        - otlphttp/loki
        - debug

    traces:
      receivers:
        - otlp
      processors:
        - resource
        - batch
      exporters:
        - otlp/tempo
        - debug